# Generated by Django 2.2.28 on 2022-10-10 19:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import utils.fields.timestamped


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.fields.timestamped.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', utils.fields.timestamped.AutoModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Título')),
                ('resenha', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resenha')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
            },
        ),
    ]
