# Generated by Django 2.2.28 on 2023-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20221026_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='cidade_interesse',
            field=models.CharField(default='', max_length=255, verbose_name='Cidade de interesse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='cidade_reside',
            field=models.CharField(default='', max_length=255, verbose_name='Cidade onde reside'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email_newsletter',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
