# Generated by Django 2.2.28 on 2022-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_auto_20221010_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='legenda',
            field=models.CharField(blank=True, max_length=255, verbose_name='legenda'),
        ),
    ]
