# Generated by Django 2.2.28 on 2022-10-09 17:16

from django.db import migrations, models
import django.utils.timezone
import utils.fields.telefone
import utils.fields.timestamped


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.fields.timestamped.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', utils.fields.timestamped.AutoModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email_newsletter', models.EmailField(max_length=254, unique=True, verbose_name='Email de Contato')),
                ('telefone', utils.fields.telefone.TelefoneField(blank=True, max_length=15, verbose_name='Telefone com DDD')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-id'],
            },
        ),
    ]
