# Generated by Django 2.2.28 on 2022-10-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-id'], 'verbose_name': 'Formulário de Franquia', 'verbose_name_plural': 'Formulário de Franquia'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email_newsletter',
            field=models.EmailField(max_length=254, verbose_name='Email de Contato'),
        ),
    ]
