# Generated by Django 2.2.28 on 2022-10-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimento',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
    ]
