# Generated by Django 2.2 on 2020-03-12 12:52

from django.db import migrations, models
import django.utils.timezone
import utils.fields.timestamped


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.fields.timestamped.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', utils.fields.timestamped.AutoModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Título da Página')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Description')),
                ('page', models.PositiveSmallIntegerField(choices=[(1, 'Home')], unique=True, verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Página estática',
                'verbose_name_plural': 'Páginas estáticas',
                'ordering': ['page'],
            },
        ),
    ]
