# Generated by Django 2.2.27 on 2022-04-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='link_whatsapp',
            field=models.CharField(blank=True, help_text='Ex.: https://wa.me/5516988888888', max_length=255, verbose_name='Link do whatsApp'),
        ),
    ]
