# Generated by Django 2.2.28 on 2022-10-10 17:40

from django.db import migrations, models
import django.utils.timezone
import utils.fields.timestamped


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.fields.timestamped.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', utils.fields.timestamped.AutoModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('legenda', models.CharField(max_length=255, verbose_name='Legenda')),
            ],
        ),
    ]
