# Generated by Django 2.2.27 on 2022-03-31 19:28

from django.db import migrations, models
import django.utils.timezone
import utils.fields.timestamped


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.fields.timestamped.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', utils.fields.timestamped.AutoModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('link_whatsapp', models.URLField(blank=True, help_text='Ex.: https://wa.me/55988888888', verbose_name='Link do whatsApp')),
            ],
            options={
                'verbose_name': 'Informações para contato',
                'verbose_name_plural': 'Informações para contato',
            },
        ),
    ]
