# Generated by Django 2.2.28 on 2022-10-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franquias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficios',
            old_name='nome',
            new_name='titulo',
        ),
    ]
