# Generated by Django 2.2 on 2020-03-12 12:52

from django.db import migrations, models
import django.utils.timezone
import utils.fields.timestamped


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedHTML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', utils.fields.timestamped.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', utils.fields.timestamped.AutoModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Atualizado em')),
                ('tag', models.PositiveSmallIntegerField(choices=[(1, 'Head'), (2, 'Body')], help_text='O código será inserido antes da tag correspondente ser fechada no html', unique=True, verbose_name='Elemento')),
                ('html', models.TextField(blank=True, verbose_name='Html')),
            ],
            options={
                'verbose_name': 'HTML Incorporado',
                'verbose_name_plural': 'HTML Incorporado',
                'ordering': ['tag'],
            },
        ),
    ]
