# Generated by Django 2.2.28 on 2022-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20221026_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email_newsletter',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email de Contato'),
        ),
    ]
